#!/bin/bash

if [[ "$#" > 0 ]]; then
  MACPORTS="$1"; shift
fi

: ${MACPORTS:="$(cd -P -- "$(dirname -- "${BASH_SOURCE}")/.." && pwd -P)/local"}
export MACPORTS

export PATH="::macports::$MACPORTS/bin:$MACPORTS/sbin::macports::$PATH"
hash -r

export MANPATH="::macports::$MACPORTS/share/man::macports::/usr/share/man"

export CFLAGS="-O2 -arch x86_64"
export LDFLAGS="-L$MACPORTS/lib"
export CPPFLAGS="-I$MACPORTS/include"
export CC="$MACPORTS/bin/gcc"
export CXX="$MACPORTS/bin/g++"
