#!/bin/bash

#/ NAME
#/     build -- builds macports, ports
#/           -- builds static site using jekyll
#/
#/ SYNOPSIS
#/     build macports|ports
#/     build site

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"

# load a meat library
source "$shome/libexec/_treadstone" "$@"

# entry point
function mpmain {
  # x11
  $cmd_port xinit
  $cmd_port xorg-server xmodmap xsetroot xterm xtermcontrol
  $cmd_port xv xpdf xprop xwininfo
  
  $cmd_port xdotool
  defaults write org.macports.X11 enable_test_extensions -boolean true 
}

require macports "$BASH_SOURCE" "$@"
