#!/bin/bash

#/ NAME
#/     build -- builds macports, ports
#/           -- builds static site using jekyll
#/
#/ SYNOPSIS
#/     build macports|ports
#/     build site

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"

# load a meat library
source "$shome/libexec/_treadstone" "$@"

# entry point
function mpmain {
  # secrets
  $cmd_port gnupg gpg-agent
  $cmd_port tcp_wrappers openssh
  $cmd_port openvpn
}

require macports "$BASH_SOURCE" "$@"
