#!/bin/bash

#/ NAME
#/     build -- builds macports, ports
#/           -- builds static site using jekyll
#/
#/ SYNOPSIS
#/     build macports|ports
#/     build site

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"

# load a meat library
source "$shome/libexec/_treadstone" "$@"

# entry point
function mpmain {
  PATH="$HOME/.cabal:$PATH"
  PATH="$HOME/Library/Haskell/bin:$PATH"

  #port -f uninstall xkeyboard-config
  #port clean xkeyboard-config
  #port -s install xkeyboard-config

  build_ghc
  build_cabal

  cabal update
  cabal install --disable-library-profiling xmonad-0.10
  cabal install --disable-library-profiling xmonad-contrib-0.10
  cabal install xmobar-0.14

  xmonad --recompile
}

function build_ghc {
  if [[ "$FLAGS_ghc" = "$FLAGS_TRUE" ]]; then
    set -x
    local tmp_ghc="$(mktemp -d -t XXXXXXXXX)"
    tar xvfz "xmonad/ghc-7.4.2-src.tar.bz2" -C "$tmp_ghc"
    pushd "$tmp_ghc/ghc-7.4.2"
    ./configure --prefix=$MACPORTS --with-iconv-includes=$MACPORTS/include --with-iconv-libraries=$MACPORTS/lib
    perl -pe 's{(AR_STAGE0 = )/Developer(/usr/bin/ar)}{$1'"$(xcode-select -print-path)"'$2}' -i "mk/config.mk"
    make -j "$FLAGS_cpus" || make -j "$FLAGS_cpus"
    make install
    popd
    rm -rf "$tmp_ghc"
    set +x
  else
    $cmd_port ghc
  fi
}

function build_cabal {
  if [[ "$FLAGS_cabal" = "$FLAGS_TRUE" ]]; then
    local tmp_cabal="$(mktemp -d -t XXXXXXXXX)"
    tar xvfz "xmonad/cabal-install-0.14.0.tar.gz" -C "$tmp_cabal"
    pushd "$tmp_cabal/cabal-install-0.14.0"
    bash bootstrap.sh 
    popd
    rm -rf "$tmp_cabal"
  else
    $cmd_port hs-cabal
  fi
}

require macports "$BASH_SOURCE" "$@"
