#!/bin/bash

#/ NAME
#/     setup -- one time setup for xcode
#/
#/ SYNOPSIS
#/     setup macports

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"

# load a meat library
source "$shome/bin/_treadstone" "$@"

# define command line options:
#   var name, default, description, short option
DEFINE_string 'install' "${MACPORTS:-$shome/local}" 'macports install' 'I'

# entry point
function main {
  require 'profile'

  export MACPORTS="$FLAGS_install"

  dir_software="${MACPORTS//\//_}"
  mkdir -p "$shome/vault/macports/distfiles"
  mkdir -p "$shome/vault/macports/software/$dir_software"
  mkdir -p "$MACPORTS"
  ln -vnfs "$shome/vault/macports/software/$dir_software" "$MACPORTS/software"
}

require sub "$BASH_SOURCE" "$@"
