#!/bin/bash

#/ NAME
#/     sign-macports -- signs and verifies macport packages with PEM certiicates
#/
#/ SYNOPSIS
#/     sign-macports

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"

# load a meat library
source "$shome/libexec/_treadstone" "$@"

# define command line options:
#   var name, default, description, short option
DEFINE_string 'install' "${MACPORTS:-$shome/local}" 'directory containing macports bin, var' '-I'
DEFINE_string 'sign' "$shome/keys/local-privkey.pem" 'signing private PEM certificate'
DEFINE_string 'verify' "$shome/keys/local-pubkey.pem" 'verifying public PEM certificate'

# entry point
function main {
  export MACPORTS="$FLAGS_install"
  find "$MACPORTS/var/macports/software" -name '*.tbz2' -print -exec openssl dgst -ripemd160   -sign "$FLAGS_sign"         -out '{}.rmd160' '{}' ';'
  find "$MACPORTS/var/macports/software" -name '*.tbz2' -print -exec openssl dgst -ripemd160 -verify "$FLAGS_verify" -signature '{}.rmd160' '{}' ';'
}

require sub "$BASH_SOURCE" "$@"
